USE sakila;

DELIMITER ||
CREATE PROCEDURE INSERT_FILM(IN IDENTIFIANT_FILM SMALLINT, 
IN TITRE VARCHAR(45), IN DESCRIPTION_DU_FILM TEXT , 
IN ANNEE_SORTIE YEAR, IN IDENTIFIANT_LANGUAGE TINYINT,
IDENTIFIANT_LANGUAGE_ORIGINAL TINYINT,
DUREE_LOCATION TINYINT, TAUX_LOCATION DECIMAL(4,2),
LONGUEUR_TEMPS_FILM SMALLINT,
COUT_DE_REMPLACEMENT DECIMAL(5,2),
EVALUATION ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'),
PARTICULARITE SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'),
DERNIERE_MODIF TIMESTAMP)
BEGIN
	IF EXISTS (SELECT * FROM film WHERE film_id = IDENTIFIANT_FILM)
		THEN 
		SIGNAL SQLSTATE "64646"
			SET MESSAGE_TEXT = 'choissisez une autre valeur pour IDENTIFIANT_FILM';
	END IF;
	IF NOT EXISTS
    #(language_id)
    END IF;
    
    IF NOT EXISTS
    #(original_language_id)
    END IF;
		
	INSERT INTO film(actor_id, first_name, last_name, last_update)
	VALUES(IDENTIFIANT , PRENOM, NOM, DERNIERE_MODIF);
	
	
    


DELIMITER ||
CREATE PROCEDURE UPDATE_FILM(IN IDENTIFIANT_FILM SMALLINT, 
IN TITRE VARCHAR(45), IN DESCRIPTION_DU_FILM TEXT , 
IN ANNEE_SORTIE YEAR, IN IDENTIFIANT_LANGUAGE TINYINT,
IDENTIFIANT_LANGUAGE_ORIGINAL TINYINT,
DUREE_LOCATION TINYINT, TAUX_LOCATION DECIMAL(4,2),
LONGUEUR_TEMPS_FILM SMALLINT,
COUT_DE_REMPLACEMENT DECIMAL(5,2),
EVALUATION ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'),
PARTICULARITE SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'),
DERNIERE_MODIF TIMESTAMP)
BEGIN
	IF EXISTS (SELECT * FROM film WHERE film_id = IDENTIFIANT_FILM)
		THEN 
		SIGNAL SQLSTATE "64646"
			SET MESSAGE_TEXT = 'choissisez une autre valeur pour IDENTIFIANT_FILM';
	END IF;
	IF NOT EXISTS
    #(language_id)
    #END IF;
    
    #IF NOT EXISTS
    #(original_language_id)
    #END IF;
	
    #UPDATE film 
    #SET film_id = IDENTIFIANT_FILM ,
    #title = TITRE ,
    #description = DESCRIPTION_DU_FILM,
    #release_year = ANNEE_SORTIE ,
    #language_id = IDENTIFIANT_LANGUAGE ,
    #original_language_id = IDENTIFIANT_LANGUAGE_ORIGINAL , 
    #rental_duration = DUREE_LOCATION ,
    #rental_rate = TAUX_LOCATION ,
    #lenght = LONGUEUR_TEMPS_FILM ,
    #remplacement_cost = COUT_DE_REMPLACEMENT ,
    #rating = EVALUATION ,
    #special_features = PARTICULARITE ,
    #last_update = DERNIERE_MODIF
    #WHERE film_id = IDENTIFIANT_FILM;
#END|| 
DELIMITER ;

CALL UPDATE_FILM(430,TITRE,DESCRIPTION_DU_FILM,ANNEE_SORTIE
,IDENTIFIANT_LANGUAGE,IDENTIFIANT_LANGUAGE_ORIGINAL,
 DUREE_LOCATION, TAUX_LOCATION,LONGUEUR_TEMPS_FILM,
 COUT_DE_REMPLACEMENT, EVALUATION, PARTICULARITE,
 DERNIERE_MODIF)



#CALL UPDATE_FILM(430,TITRE,DESCRIPTION_DU_FILM,ANNEE_SORTIE
#,IDENTIFIANT_LANGUAGE,IDENTIFIANT_LANGUAGE_ORIGINAL,
# DUREE_LOCATION, TAUX_LOCATION,LONGUEUR_TEMPS_FILM,
# COUT_DE_REMPLACEMENT, EVALUATION, PARTICULARITE,
# DERNIERE_MODIF)









DELIMITER ||
CREATE PROCEDURE RETRIEVE_FILM_BY_TITLE(IN TITRE VARCHAR(45))
BEGIN
	SELECT film_id AS IDENTIFIANT_FILM, title AS TITRE FROM film
    WHERE title = TITRE ;
END ||
DELIMITER ;

CALL RETRIEVE_FILM_BY_TITLE("HOOK CHARIOTS"); 