#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 20 14:38:52 2020

@author: virus
"""


import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://user:password@127.0.0.1:3306/ASSURAUTO')

data = pd.read_sql_query('SELECT * FROM CLIENTS',engine)
print(data)


#CL_ID = '21'
#CL_NOM = 'Un certain club'

#engine.execute('INSERT INTO CONTRAT (CL_ID, CL_NOM) VALUES (%s, "%s");' %(CL_ID , CL_NOM))

CL_NOM = ""
CL_PRENOM = ""
CL_ADRESSE = ""
CL_CODEPOSTAL = ""
CL_VILLE = ""
CL_TELEPHONE = ""
CL_MAIL = ""
CL_FAX = ""

id = pd.read_sql_query("SELECT max(CL_ID) FROM CLIENTS;",engine)+1

while len(CL_NOM)==0 or len(CL_PRENOM)==0 or len(CL_ADRESSE)==0 or len(CL_CODEPOSTAL)==0 or len(CL_VILLE)==0 or len(CL_TELEPHONE) or len(CL_MAIL) : 
    
    if len(CL_NOM)==0:
        CL_NOM = input('Veillez entrez le nom du client : ')
    
    elif len(CL_PRENOM)==0: 
        CL_PRENOM = input('Veillez entrez le prénom du client : ')
    
    elif len(CL_TELEPHONE)==0: 
        CL_TELEPHONE = input("Veillez entrez le numéro de téléphone du client : ")
    
    elif len(CL_MAIL)==0:
        CL_MAIL = input("Veillez entrez  l'email du client : ")
    
    elif len(CL_FAX)==0:
        CL_FAX = input("Veillez entrez le numéro de fax du client : ")

    
    elif len(CL_ADRESSE)==0: 
        CL_ADRESSE = input("Veillez entrez l'addresse du client : ")
    
    elif len(CL_VILLE)==0:
        CL_VILLE = input("Veillez entrez la ville du client : ")
    
    
    elif len(CL_CODEPOSTAL)==0: 
        CL_CODEPOSTAL = input("Veillez entrez le code postal du client : ")
        if CL_CODEPOSTAL.isdigit():
            CL_CODEPOSTAL = CL_CODEPOSTAL
        else:
            print("Veuillez entrez que des nombres")
            CL_CODEPOSTAL = ""
    



engine.execute('INSERT INTO CLIENTS (CL_ID, CL_NOM, CL_PRENOM, CL_TELEPHONE, CL_MAIL, CL_FAX, CL_ADDRESSE , CL_VILLE, CL_CODEPOSTAL) VALUES ();')


	
