USE sakila ;
SELECT * FROM actor;

CALL RETRIEVE_ACTOR(22);
CALL RETRIEVE_ACTOR_2(22);
CALL RETRIEVE_ACTOR_3(2034);

CALL RETRIEVE_ACTOR_BY_NOM_PRENOM("Anthony","MARAIS");


CALL CREATE_ACTOR(2034, "Anthony", "MARAIS", NOW());


CALL CREATE_ACTOR_2("Anthony", "MARAIS", NOW());

CALL DELETE_ACTOR (2036);

CALL UPDATE_ACTOR (2037, "ANTHONY" , "MARIAS" , NOW());



CALL RETRIEVE_FILM_BY_TITLE("HOOK CHARIOTS"); 