USE sakila ;

#### PROCEDURE STOCKER RECHERCHE D'ACTEUR PAR SON ID ####

DELIMITER ||
CREATE PROCEDURE RETRIEVE_ACTOR( IN ID_ACTOR SMALLINT )
BEGIN
	SELECT actor_id AS IDENTIFIANT, first_name AS PRENOM, last_name AS NOM, last_update AS DERNIERE_MODIF FROM actor
    WHERE actor_id = ID_ACTOR;
END||

CREATE PROCEDURE RETRIEVE_ACTOR_2( IN ID_ACTOR SMALLINT )
BEGIN
	SELECT * FROM actor
    WHERE actor_id = ID_ACTOR;
END||

CREATE PROCEDURE RETRIEVE_ACTOR_3( IN ID_ACTOR SMALLINT )
BEGIN
	SELECT first_name AS PRENOM, last_name AS NOM FROM actor
    WHERE actor_id = ID_ACTOR;
END||
DELIMITER ; 

#### FIN DE PROCEDURE ####

#DROP PROCEDURE ACTOR;
#DROP PROCEDURE ACTOR_2;
#DROP PROCEDURE ACTOR_3;

### CALL DES PROCEDURE ####
CALL RETRIEVE_ACTOR(22);
CALL RETRIEVE_ACTOR_2(22);
CALL RETRIEVE_ACTOR_3(22);

#### FIN DES CALL ####

#### PROCEDURE STOCKEE RETROUVER INFO ACTEUR VIA PRENOM/NOM ####

DELIMITER ||
CREATE PROCEDURE RETRIEVE_ACTOR_BY_NOM_PRENOM(IN PRENOM VARCHAR(45), IN NOM VARCHAR(45) )
BEGIN
	SELECT actor_id AS IDENTIFIANT, first_name AS PRENOM, last_name AS NOM, last_update AS DERNIERE_MODIF FROM actor
    WHERE first_name = PRENOM AND last_name = NOM ;
END ||
DELIMITER;


#### FIN PROCEDURE ####

CALL RETRIEVE_ACTOR_BY_NOM_PRENOM("Anthony","MARAIS");





### PROCEDURE CREATION D'ACTEUR ###
DELIMITER ||

CREATE PROCEDURE CREATE_ACTOR(IN IDENTIFIANT SMALLINT, IN PRENOM VARCHAR(45), IN NOM VARCHAR(45), IN DERNIERE_MODIF TIMESTAMP )
BEGIN
	IF EXISTS (SELECT * FROM actor WHERE actor_id = IDENTIFIANT)
	THEN 
		SIGNAL SQLSTATE "64646"
			SET MESSAGE_TEXT = 'choissisez une autre valeur pour ID';
	ELSE
		INSERT INTO actor(actor_id, first_name, last_name, last_update)
		VALUES(IDENTIFIANT , PRENOM, NOM, DERNIERE_MODIF);
	END IF;
END||

DELIMITER ;

#### FIN DE PROCEDURE ####

CALL CREATE_ACTOR(2034, "Anthony", "MARAIS", NOW());

#DROP PROCEDURE CREATE_ACTOR;


DELIMITER ||

CREATE PROCEDURE CREATE_ACTOR_2(IN PRENOM VARCHAR(45), IN NOM VARCHAR(45), IN DERNIERE_MODIF TIMESTAMP )
BEGIN
	INSERT INTO actor(first_name, last_name, last_update)
		VALUES(PRENOM, NOM, DERNIERE_MODIF);
END||

DELIMITER ;


##DROP PROCEDURE CREATE_ACTOR_2;
CALL CREATE_ACTOR_2("Anthony", "MARAIS", NOW());





SELECT * FROM actor
ORDER BY actor_id DESC;


CALL RETRIEVE_ACTOR_BY_NOM_PRENOM("ANTHONY","MARIAS");




DELIMITER ||
CREATE PROCEDURE DELETE_ACTOR(IN IDENTIFIANT SMALLINT)
BEGIN
	DELETE FROM actor WHERE actor_id = IDENTIFIANT ;
END|| 
DELIMITER ;

CALL DELETE_ACTOR (2036);

DROP PROCEDURE DELETE_ACTOR;

DELIMITER ||
CREATE PROCEDURE UPDATE_ACTOR(IN IDENTIFIANT SMALLINT, IN PRENOM VARCHAR(45), IN NOM VARCHAR(45), IN DERNIERE_MODIF TIMESTAMP)
BEGIN
	UPDATE actor 
    SET first_name = PRENOM ,
    last_name = NOM ,
    last_update = DERNIERE_MODIF
    WHERE actor_id = IDENTIFIANT
    ;
END|| 
DELIMITER ;

CALL UPDATE_ACTOR (2037, "ANTHONY" , "MARIAS" , NOW())