use netflix;

SELECT CATALOGUE.title , ACTOR.cast , DIRECTOR.director, CATALOGUE.release_year 
FROM CATALOGUE 
JOIN DIRECTOR_CATALOGUE ON CATALOGUE.show_id = DIRECTOR_CATALOGUE.show_id 
JOIN DIRECTOR ON DIRECTOR_CATALOGUE.director_id = DIRECTOR.director_id 
JOIN ACTOR_CATALOGUE ON CATALOGUE.show_id = ACTOR_CATALOGUE.show_id 
JOIN ACTOR ON ACTOR_CATALOGUE.cast_id = ACTOR.cast_id ;


use netflix;



SELECT CATALOGUE.title , CATALOGUE.type, CATALOGUE.duration, DIRECTOR.director, CATEGORY.listed_in , ACTOR.cast , CATALOGUE.release_year , COUNTRY.country
FROM CATALOGUE
JOIN DIRECTOR_CATALOGUE ON CATALOGUE.show_id = DIRECTOR_CATALOGUE.show_id 
JOIN DIRECTOR ON DIRECTOR_CATALOGUE.director_id = DIRECTOR.director_id 
JOIN CATEGORY_CATALOGUE ON CATALOGUE.show_id = CATEGORY_CATALOGUE.show_id 
JOIN CATEGORY ON CATEGORY_CATALOGUE.listed_in_id = CATEGORY.listed_in_id 
JOIN ACTOR_CATALOGUE ON CATALOGUE.show_id = ACTOR_CATALOGUE.show_id 
JOIN ACTOR ON ACTOR_CATALOGUE.cast_id = ACTOR.cast_id 
JOIN COUNTRY_CATALOGUE ON CATALOGUE.show_id = COUNTRY_CATALOGUE.show_id 
JOIN COUNTRY ON COUNTRY_CATALOGUE.country_id = COUNTRY.country_id;